[workspace]
resolver = "3"
members = ["nt_client"]

[workspace.package]
edition = "2024"
repository = "https://github.com/DatAsianBoi123/nt_client"
license = "MIT"
authors = ["Zachary Su <contact@datasiqn.com>"]

